app/routes.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    flash,
    session,
    abort,
    request,
)
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from app.models import User, BlogPost, Comment
from app.forms import BlogPostForm, RegisterForm, LoginForm, CommentForm, ContactFrom
from app import db
from flask import current_app
from functools import wraps
import bleach
import resend


# Sanitize content from User input
def sanitize(text):
    allowed_tags = current_app.config["ALLOWED_TAGS"]
    allowed_attributes = current_app.config["ALLOWED_ATTRIBUTES"]
    return bleach.clean(
        text, tags=allowed_tags, attributes=allowed_attributes, strip=True
    )


# Create a Blueprint for routes
routes_bp = Blueprint("routes", __name__)


# Admin-only decorator
def admin_only(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if session.get("is_admin"):
            return func(*args, **kwargs)
        else:
            return abort(403)

    return wrapper


def author_only(func):
    @wraps(func)
    def wrapper(post_id, *args, **kwargs):
        post = BlogPost.query.get_or_404(post_id)
        if post.author == current_user:
            return func(post_id, *args, **kwargs)
        else:
            return abort(403)  # Forbidden

    return wrapper


# Context processor for template rendering
@routes_bp.app_context_processor
def context_processor():
    return dict(
        logged_in=session.get("logged_in", False),
        is_admin=session.get("is_admin", False),
        current_user=current_user,
    )


# User registration
@routes_bp.route("/register", methods=["GET", "POST"])
def register():
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        if User.query.filter_by(email=register_form.email.data).first():
            flash("This user already exists. Please login instead.", "warning")
            return redirect(url_for("routes.login"))
        new_user = User(
            username=register_form.username.data,
            email=register_form.email.data,
            password=generate_password_hash(register_form.password.data),
        )
        try:
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            session["logged_in"] = True
            flash("Registration successful!", "success")
            return redirect(url_for("routes.get_posts"))
        except Exception as e:
            db.session.rollback()
            flash(f"An error occurred: {str(e)}", "danger")
    return render_template("register.html", form=register_form)


# User login
@routes_bp.route("/login", methods=["GET", "POST"])
def login():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(email=login_form.email.data).first()
        if user and check_password_hash(user.password, login_form.password.data):
            login_user(user)
            session["is_admin"] = user.id == 1
            session["logged_in"] = True
            return redirect(url_for("routes.get_posts"))
        flash("Invalid email or password.")
    return render_template("login.html", form=login_form)


# User logout
@routes_bp.route("/logout")
@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for("routes.get_posts"))


# Display Newest 10 posts
@routes_bp.route("/")
def get_posts():
    posts = BlogPost.query.limit(10).all()
    return render_template("index.html", posts=posts)


# Display all posts
@routes_bp.route("/all_posts")
def show_all_posts():
    posts = BlogPost.query.all()
    return render_template("all-posts.html", all_posts=posts)


# Show individual post
@routes_bp.route("/post/<int:post_id>", methods=["GET", "POST"])
def show_post(post_id):
    post = BlogPost.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        comment = Comment(
            text=sanitize(form.comment_text.data),
            comment_author=current_user,
            parent_post=post,
        )
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for("routes.show_post", post_id=post.id))

    sanitized_post_body = sanitize(post.body)
    sanitized_comments_text = [sanitize(comment.text) for comment in post.comments]
    comments_with_sanitized_text = zip(post.comments, sanitized_comments_text)
    return render_template(
        "post.html",
        post=post,
        form=form,
        sanitized_post_body=sanitized_post_body,
        comments_with_sanitized_text=comments_with_sanitized_text,
    )


# Add a new post
@routes_bp.route("/new-post", methods=["GET", "POST"])
@login_required
def add_new_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        new_post = BlogPost(
            title=form.title.data,
            subtitle=form.subtitle.data,
            body=sanitize(form.body.data),
            img_url=form.img_url.data,
            author=current_user,
        )
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for("routes.get_posts"))
    return render_template("make-post.html", form=form)


# Edit a post
@routes_bp.route("/edit-post/<int:post_id>", methods=["GET", "POST"])
@login_required
@author_only
def edit_post(post_id):
    post = BlogPost.query.get_or_404(post_id)
    form = BlogPostForm(obj=post)
    if form.validate_on_submit():
        post.title = form.title.data
        post.subtitle = form.subtitle.data
        post.body = sanitize(form.body.data)
        post.img_url = form.img_url.data
        db.session.commit()
        return redirect(url_for("routes.show_post", post_id=post.id))
    return render_template("make-post.html", form=form, is_edit=True)


# Delete a post
@routes_bp.route("/delete/<int:post_id>")
@login_required
@author_only
def delete_post(post_id):
    post = BlogPost.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for("routes.get_posts"))


# About page
@routes_bp.route("/about")
def about():
    return render_template("about.html")


# Contact page
@routes_bp.route("/contact", methods=["GET", "POST"])
def contact():
    # Load the RESEND API KEY from app
    resend.api_key = current_app.config["RESEND_API_KEY"]
    resend_sender = current_app.config["RESEND_SENDER"]
    resend_receiver = current_app.config["RESEND_RECEIVER"]

    if request.method == "POST":
        params: resend.Emails.SendParams = {
            "from": f"Blobby <{resend_sender}>",
            "to": resend_receiver,
            "subject": f"{request.form['name']} has sent a messsage!!!",
            "html": f"Name: {request.form['name']}<br />E-mail: {request.form['email']}<br />Message: {request.form['message']}",
        }
        resend.Emails.send(params)
        return render_template("contact.html", msg_sent=True)
    else:
        if current_user.is_authenticated:
            name = current_user.username
            email = current_user.email
        else:
            name = ""
            email = ""
        return render_template(
            "contact.html",
            msg_sent=False,
            name=name,
            email=email,
            current_user=current_user,
        )


# Account page
@routes_bp.route("/account/<int:user_id>")
def account(user_id):
    # Get the current user's posts sorted in descending order of date
    user = User.query.get(user_id)
    if not user:
        abort(404)
    posts = BlogPost.query.filter_by(author=user).all()

    # Render the account page with user information and their posts
    return render_template(
        "account.html",
        user=user,
        posts=posts,
    )


@routes_bp.route("/my-account")
@login_required
def my_account():
    return redirect(url_for("routes.account", user_id=current_user.id))


@routes_bp.route("/edit-account", methods=["GET", "POST"])
@login_required
def edit_account():
    if request.method == "POST":
        new_username = request.form.get("username")
        new_email = request.form.get("email")

        # Check for unique email
        if User.query.filter(
            User.email == new_email, User.id != current_user.id
        ).first():
            flash("This email is already in use by another account.", "danger")
            return redirect(url_for("routes.edit_account"))

        # Update user information
        current_user.username = new_username
        current_user.email = new_email

        try:
            db.session.commit()
            flash("Account information updated successfully!", "success")
            return redirect(url_for("routes.account"))
        except Exception as e:
            db.session.rollback()
            flash(f"An error occurred: {str(e)}", "danger")

    return render_template("edit-account.html", user=current_user)

app/templates/about.html
{% include "header.html" %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('../static/assets/img/about-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>About SAM</h1>
          <span class="subheading">I am a Computer Engineer & Tech Enthusiast</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>Hi there! I'm Sameet Patil, but you can call me SAM. I'm a passionate computer engineering student based in
          Pune, India.
          With a keen interest in the realms of Artificial Intelligence (AI) and Machine Learning (ML), I'm continually
          fascinated
          by the innovative solutions these fields offer to real-world problems.</p>
        <h3>Academic Pursuits</h3>
        <p>Currently pursuing my degree in Computer Engineering, I'm dedicated to exploring the intricacies of software
          development, algorithms, and system architecture. My academic journey has equipped me with a solid foundation
          in various
          programming languages and concepts, with Python being my primary tool of choice.</p>
        <h3>Python Developer</h3>
        <p>As a Python developer, I thrive on turning ideas into reality through code. Whether it's crafting robust web
          applications, building efficient algorithms, or automating mundane tasks, Python serves as my trusty companion
          in
          bringing projects to life. With experience in frameworks like Flask, I'm adept at developing scalable and
          user-friendly
          web solutions.</p>
        <h3>Passion for AI and ML</h3>
        <p>My fascination with AI and ML goes beyond the classroom. I'm deeply intrigued by the potential of these
          technologies to
          revolutionize industries and enhance human capabilities. From predictive analytics to natural language
          processing, I'm
          committed to exploring the endless possibilities AI and ML offer.</p>
        <h3>Building with Flask and Bootstrap</h3>
        <p>The website you're currently exploring is a testament to my dedication to learning and growing as a
          developer. Crafted
          entirely in Python using the Flask framework and enhanced with Bootstrap, this project represents my journey
          in
          mastering web development tools and techniques. From responsive designs to dynamic functionalities, every
          aspect of this
          website reflects my passion for crafting elegant and efficient solutions.</p>
        <a href="{{ url_for('routes.contact') }}">
          <h3>Get in Touch</h3>
        </a>
        <p>Interested in collaborating on a project or discussing the latest developments in AI and ML? Feel free to
          reach out! I'm
          always eager to connect with fellow enthusiasts, exchange ideas, and embark on new ventures.</p>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

app/templates/account.html
{% include "header.html" %}
{% block content %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('../static/assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{{ user.username }}'s Blob Account</h1>
                    <span class="subheading">your MIND. your EXPRESSION. your LIFE.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <!-- User Information -->
            <div class="card mb-4 position-relative">
                <div class="card-body">

                    <!-- User Information -->
                    <h4 class="card-title">User Information</h4>
                    <hr class="my-4" />
                    <!-- Gravatar at the Top-Right -->
                    <img src="{{ user.email | gravatar(size=80) }}" alt="User Avatar"
                        class="rounded position-absolute top-1 end-0 m-3 mt-1" />

                    <p class="card-text" style="margin: 0.5rem 0;"><strong>Username:</strong> {{ user.username }}</p>
                    {% if current_user.is_authenticated and current_user==user %}
                    <p class="card-text" style="margin: 0.5rem 0;"><strong>Email:</strong> {{ user.email }}</p>
                    {% endif %} 
                    <p class="card-text" style="margin: 0.5rem 0;"><strong>Joined:</strong> {{ user.date_joined.strftime('%d-%m-%Y') }}</p>
                    <p class="card-text" style="margin: 0.5rem 0;"><strong>No of Posts:</strong> {{ posts.__len__() }}</p>
                    {% if current_user.is_authenticated and current_user==user %}
                    <a href="{{ url_for('routes.edit_account') }}" class="btn btn-primary mt-3">Edit Account Info</a>
                    {% endif %}
                </div>
            </div>

            <!-- New Post Button -->
            {% if current_user.is_authenticated and current_user==user %}
            <div class="d-flex justify-content-end mb-4">
                <div class="sticky-top"><a class="btn btn-primary float-right"
                        href="{{ url_for('routes.add_new_post') }}">Create New
                        Post</a></div>
            </div>
            {% endif %}

            <!-- User's Posts -->
            <h3 class="mb-4">{{ user.username }}'s Blobs</h3>
            <hr class="my-4" />

            {% for post in posts %}
            <div class="post-preview">
                <a href="{{ url_for('routes.show_post', post_id=post.id) }}">
                    <h2 class="post-title">{{ post.title }}</h2>
                    <h3 class="post-subtitle">{{ post.subtitle }}</h3>
                </a>
                <p class="post-meta">
                    Posted by <u>{{ post.author.username }}</u> on {{ post.date.strftime('%d-%m-%Y') }}
                    <!-- Delete Post -->
                    {% if current_user.is_authenticated and post.author == current_user %}
                    <a href="{{ url_for('routes.delete_post', post_id=post.id) }}" class="text-danger ms-2">✘</a>
                    {% endif %}
                </p>
            </div>
            <!-- Divider -->
            <hr class="my-4" />
            {% endfor %}

            <!-- No Posts Fallback -->
            {% if posts|length == 0 %}
            <p class="text-center">You haven't created any blobs yet. Start expressing yourself!</p>
            {% endif %}
        </div>
    </div>
</div>

{% include "footer.html" %}
{% endblock %}

app/templates/all-posts.html
{% include "header.html" %}

<!-- Page Header-->
{% block content %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('../static/assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Blobs</h1>
                    <span class="subheading">your MIND. your EXPRESSION. your LIFE.</span>
                </div>
            </div>
        </div>
    </div>
</header>


<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            {% for post in all_posts %}
            <div class="post-preview">
                <a href="{{ url_for('routes.show_post', post_id=post.id) }}">
                    <h2 class="post-title">{{ post.title }}</h2>
                    <h3 class="post-subtitle">{{ post.subtitle }}</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="{{ url_for('routes.account', user_id=post.author.id) }}"><u>{{ post.author.username
                            }}</u></a>
                    on {{post.date.strftime('%d-%m-%Y')}}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}

            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-secondary text-uppercase" href="{{url_for('routes.get_posts')}}">Home</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% include "footer.html" %}

app/templates/all_posts.html
{% include "header.html" %}

<!-- Page Header-->
<div>
    <header>
        <h1>Blobs</h1>
    </header>
</div>

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            {% for post in all_posts %}
            <div class="post-preview">
                <a href="{{ url_for('routes.show_post', post_id=post.id) }}">
                    <h2 class="post-title">{{ post.title }}</h2>
                    <h3 class="post-subtitle">{{ post.subtitle }}</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#">{{ post.author.username }}</a>
                    on {{post.date}}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}

            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-secondary text-uppercase" href="{{url_for('routes.get_posts')}}">Home</a>
            </div>
        </div>
    </div>
</div>

app/templates/contact.html
{% include "header.html" %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('../static/assets/img/contact-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          {% if msg_sent: %}
          <h1>Successfully sent your message</h1>
          {% else: %}
          <h1>Contact Me</h1>
          {% endif %}
          <span class="subheading">Have questions? I have answers.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          Want to get in touch? Fill out the form below to send me a message and
          I will get back to you as soon as possible!
        </p>
        <div class="my-5">
          <form id="contactForm" name="sentMessage" action="{{ url_for('routes.contact') }}" method="post">
            <div class="form-floating">
              <input class="form-control" id="name" name="name" type="text" value="{{ name }}"
                placeholder="Enter your name..." required />
              <label for="name">Name</label>
            </div>
            <div class="form-floating">
              <input class="form-control" id="email" name="email" type="email" value="{{ email }}"
                placeholder="Enter your email..." required />
              <label for="email">Email address</label>
            </div>
            <div class="form-floating">
              <textarea class="form-control" id="message" name="message" placeholder="Enter your message here..."
                required style="height: 12rem"></textarea>
              <label for="message">Message</label>
            </div>
            <br />
            <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">
              Send
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

app/templates/edit-account.html
{% include "header.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center mb-4">Edit Account Information</h2>
            <form method="POST" action="{{ url_for('routes.edit_account', user_id=user.id) }}">
                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}"
                        required />
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}"
                        required />
                </div>
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                    <a href="{{ url_for('routes.account') }}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% include "footer.html" %}
{% endblock %}

app/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Blobby</title>
  {% block styles %}
  <!-- Load Bootstrap-Flask CSS here -->
  {{ bootstrap.load_css() }}
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='assets/favicon.ico') }}" />
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
    type="text/css" />
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
    rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet" />
  {% endblock %}
</head>

<body>
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="{{ url_for('routes.get_posts') }}">
        <img id="navbar-logo" src="{{ url_for('static', filename='assets/img/blobby-light.png') }}" alt=""
          class="img-fluid" style="width: 40px; height: 40px">
        Blobby
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto py-4 py-lg-0">
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('routes.get_posts') }}">Home</a>
          </li>
          <!-- Only show Login/Register if user is logged out. Otherwise show "Log Out" -->
          {% if not current_user.is_authenticated: %}
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('routes.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('routes.register') }}">Register</a>
          </li>
          {% else: %}
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('routes.my_account') }}">My Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('routes.logout') }}">Log Out</a>
          </li>
          {% endif %}
          {%if not is_admin: %}
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('routes.about') }}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('routes.contact') }}">Contact</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</body>

</html>

app/templates/index.html
{% include "header.html" %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('../static/assets/img/home-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Blobs</h1>
          <span class="subheading">your MIND. your EXPRESSION. your LIFE.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      {% for post in posts %}
      <div class="post-preview">
        <a href="{{ url_for('routes.show_post', post_id=post.id) }}">
          <h2 class="post-title">{{ post.title }}</h2>
          <h3 class="post-subtitle">{{ post.subtitle }}</h3>
        </a>
        <p class="post-meta">
          Posted by
          <a href="{{ url_for('routes.account', user_id=post.author.id) }}"><u>{{ post.author.username }}</u></a>
          on {{ post.date.strftime('%d-%m-%Y') }}
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      {% endfor %}

      <!-- New Post -->
      {% if current_user.is_authenticated %}
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-primary float-right" href="{{url_for('routes.add_new_post')}}">Create New Post</a>
      </div>
      {% endif %}

      <!-- Pager-->
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-secondary text-uppercase" href="{{url_for('routes.show_all_posts')}}">All Posts →</a>
      </div>
    </div>
  </div>
</div>

{% include "footer.html" %}

app/templates/login.html
{% from "bootstrap5/form.html" import render_form %}
{% block content %}
{% include "header.html" %}

<!-- Page Header -->
<header class="masthead" style="background-image: url('../static/assets/img/login-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Log In</h1>
          <span class="subheading">Welcome Back!</span>
        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
  <div class="container">
    <div class="row">
      <!-- Adding Flash message here for users trying to register twice -->
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <p class="flash">{{ message }}</p>
      {% endfor %}
      {% endif %}
      {% endwith %}
      <div class="col-lg-8 col-md-10 mx-auto">
        <!--Rendering login form here-->
        {{render_form(form, novalidate=True, button_map={"submit": "primary"}) }}
      </div>
    </div>
  </div>
</main>


{% include "footer.html" %} {% endblock %}

app/templates/post.html
{% from "bootstrap5/form.html" import render_form %} {% block content %}
{% include "header.html" %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{{post.img_url}}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1>{{ post.title }}</h1>
          <h2 class="subheading">{{ post.subtitle }}</h2>
          <span class="meta">Posted by
            <a href="{{url_for('routes.account', user_id=post.author.id)}}"><u>{{ post.author.username }}</u></a>
            on {{ post.date.strftime('%d-%m-%Y') }}
          </span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <!-- {{ post.body | safe }} -->
        {{ sanitized_post_body | safe }}
        {% if current_user.is_authenticated and post.author == current_user %}
        <div class="d-flex justify-content-between mb-4">
          <!-- Edit Post -->
          <a class="btn btn-primary" href="{{ url_for('routes.edit_post', post_id=post.id) }}">Edit Post</a>
          <!-- Delete Post -->
          <a class="btn btn-danger" href="{{ url_for('routes.delete_post', post_id=post.id) }}">Delete Post</a>
        </div>
        {% endif %}


        {{ render_form(form, novalidate=True, button_map={"submit": "primary"}) }}
        <div class="comment">
          <ul class="commentList">
            <!-- {% for comment in post.comments: %} -->
            {% for comment, sanitized_comments_text in comments_with_sanitized_text %}
            <li>
              <div class="commenterImage">
                <img src="{{ comment.comment_author.email | gravatar }}" />
              </div>
              <div class="commentText">
                <!-- <p>{{ comment.text | safe }}</p> -->
                <p>{{ sanitized_comments_text | safe }}</p>
                <span class="sub-text">{{ comment.comment_author.username }}</span>
              </div>
            </li>
            {% endfor %}
            <!-- {% endfor %} -->
          </ul>
        </div>

      </div>
    </div>
  </div>
</article>

{% include "footer.html" %}
{% endblock %}